### ISSUE TITLE
大佬，有可以将多个订阅链接合并为一个订阅链接，然后按不同订阅链接分组的clash或者clash verge配置文件吗

### ISSUE THREAD

**Issue by xueli12** [abrclano/Self-use-Rules#2]
如题

**Comment by abrclano** [comment]
你的需求建议使用proxy-providers，这是Meta内核官方文档[https://wiki.metacubex.one/en/config/proxy-providers/](url)

**Comment by xueli12** [comment]
> https://wiki.metacubex.one/en/config/proxy-providers/

很感谢，我学习一下

**Comment by Zding89** [comment]
我看了下脚本没办法抓到providers里面的信息，这是目前verge的问题吗？

**Comment by abrclano** [comment]
> 我看了下脚本没办法抓到providers里面的信息，这是目前verge的问题吗？

emm，我个人猜测verge的脚本处理应该是把当前所选订阅链接作为入参去解析字段，如果使用providers的话可能就获取不到订阅链接，所以就没办法解析，具体怎么搞的得看相关的代码。你如果使用providers的话我觉得就没必要再用script了，直接用yaml就行了

**Comment by Zding89** [comment]
> > 我看了下脚本没办法抓到providers里面的信息，这是目前verge的问题吗？
> 
> emm，我个人猜测verge的脚本处理应该是把当前所选订阅链接作为入参去解析字段，如果使用providers的话可能就获取不到订阅链接，所以就没办法解析，具体怎么搞的得看相关的代码。你如果使用providers的话我觉得就没必要再用script了，直接用yaml就行了

好的，谢谢解答
