### ISSUE TITLE
大佬我一启用你的script配置 clash verge就崩了

### ISSUE THREAD

**Issue by XGntsl** [abrclano/Self-use-Rules#8]
大佬我一启用你的script配置clash verge就崩了，我全部复制过去的，不懂代码

**Comment by abrclano** [comment]
哪个版本，截图看看

**Comment by XGntsl** [comment]
> 哪个版本，截图看看

![image](https://github.com/abrclano/Meandering.Path/assets/117980999/40aa2063-3733-4948-946e-ae1bc2c8122d)

**Comment by abrclano** [comment]
我1.6.5没问题呀
![image](https://github.com/abrclano/Meandering.Path/assets/80184979/565d53fd-db06-4cdc-9426-07e2a355167d)
报的什么错，你有没有启用订阅文件

**Comment by XGntsl** [comment]
> 我1.6.5没问题呀 ![image](https://private-user-images.githubusercontent.com/80184979/337527363-565d53fd-db06-4cdc-9426-07e2a355167d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzYzMjcsIm5iZiI6MTcxNzczNjAyNywicGF0aCI6Ii84MDE4NDk3OS8zMzc1MjczNjMtNTY1ZDUzZmQtZGIwNi00Y2RjLTk0MjYtMDdlMmEzNTUxNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA0NTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2M2FkNzc2Mzc0YjNhNmNlNWVkNjU4NWU4MjhmMjRjYmI1MjEzOGJhMjlhM2QyMmQ5YzgyZDUwNTgxZTkwMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89fHlB0DvSmmFf2d-JrriLQyZHZRdxgPm1P8-EBTpTI) 报的什么错，你有没有启用订阅文件

不知道在哪里看报错，总之就是直接崩了，订阅文件一启用直接崩

**Comment by XGntsl** [comment]
> 我1.6.5没问题呀 ![image](https://private-user-images.githubusercontent.com/80184979/337527363-565d53fd-db06-4cdc-9426-07e2a355167d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzY2OTEsIm5iZiI6MTcxNzczNjM5MSwicGF0aCI6Ii84MDE4NDk3OS8zMzc1MjczNjMtNTY1ZDUzZmQtZGIwNi00Y2RjLTk0MjYtMDdlMmEzNTUxNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA0NTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMjExMGFmMjIyZTY5NWQ4ZmRmODM4M2U2MTJlZWM0ZmUxZGJhMjRiNzRjMjUzM2E4OGJmNDY0YjU2NDAzYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FEoK1pLsEwoFt4VthE4qeYHQn160KaP26I8Xv0GDdnM) 报的什么错，你有没有启用订阅文件

大佬是我的问题qaq，我重新添加了一个，没问题了

**Comment by abrclano** [comment]
ok
